services:
  php-api:
    container_name: php-api
    env_file:
        - ./api/laravel/.env
        - ./.env
    build:
      dockerfile: dev.Dockerfile
      args:
        - uid=${HOST_UID:-1000}
        - user=${HOST_USER:-takeshi}
        - gid=${HOST_GID:-1000}
        - app_root=${BACKEND_ROOT:-/var/www/html}/${LARAVEL_APP_NAME}
        - redis_version=${REDIS_VERSION:-6.0.2}
        - php_version=${PHP_VERSION:-8.2}
        - debug=${BACKEND_DEBUG:-yes}
        - tz=${TIMEZONE:-Etc/UTC}
    environment:
      - XDEBUG_CONFIG=${XDEBUG_INIT_CONF:-client_host=172.177.0.1}
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=33060
      - DB_DATABASE=${MYSQL_DB_NAME}
      - DB_USERNAME=${MYSQL_DB_USER:-laravel}
      - DB_PASSWORD=${MYSQL_DB_PASS:-}
      - APP_ENV=local
      - APP_DEBUG=${BACKEND_DEBUG:-true}
      - REDIS_HOST=redis
      - MOCK_DATA=${MOCK_DATA:-no}
    volumes:
      - ./api/laravel:${BACKEND_ROOT:-/var/www/html}/${LARAVEL_APP_NAME}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - laravel_net
    ports:
      - "8000:80"
    working_dir: ${BACKEND_ROOT:-/var/www/html}/${LARAVEL_APP_NAME}
    tty: true
    depends_on:
      - mysql
      - redis
      - artisan-cli
      - composer-cli

  api-gateway:
    build:
      context: ./api/gateway
      args:
        - node_version=${APP_NODE_VERSION:-20.12.2}
        - app_root=/home/${HOST_USER}/nuxt
        - uid=${HOST_UID:-1000}
        - user=${HOST_USER}
        - gid=${HOST_GID:-1000}
        - debug=${GATEWAY_DEBUG:-no}
        - pnpm_version=${PNPM_VERSION:-latest}
    env_file: ./.env
    networks:
      - laravel_net
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    volumes:
      - ./api/gateway:/home/${HOST_USER}/nuxt
    tty: true
    depends_on:
      - php-api

  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
      args:
        - uid=${HOST_UID:-1000}
        - user=${HOST_USER}
        - gid=${HOST_GID:-1000}
        - debug=${BACKEND_DEBUG:-yes}
        - tz=${TIMEZONE:-Etc/UTC}
        - mysql_version=${MYSQL_VERSION:-8.0}
        - root_pass=${MYSQL_DB_ROOT_PASS}
    command:
      - --mysqlx=OFF
      - --host_cache_size=0
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --log-error-verbosity=2
      - --plugin-load-add=connection_control.so
    ports:
      - "33070:33060"
    environment:
      - MYSQL_DATABASE=${MYSQL_DB_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_DB_PASS}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_ROOT_HOST=%
      - MYSQL_LOG_CONSOLE=true
      - TZ=EEST
    networks:
      - laravel_net
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/docker-my.cnf:ro
      - mysql_data_vol:/var/lib/mysql
      # - ./docker/mysql/log/mysql.log:/var/lib/mysql.log
      # - ./docker/mysql/log/error.log:/var/lib/mysql/mysql_error.log
      # - ./docker/mysql/log/mysql-slow.log:/var/lib/mysql/mysql_slow.log
    cap_add:
      - SYS_NICE
    restart: always
    tty: true
    user: "${HOST_USER}:docker"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:${REDIS_VERSION:-6.0.2}-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    sysctls:
      net.core.somaxconn: 1024
    networks:
      - laravel_net
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - redis_data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf:cached

  composer-cli:
    container_name: composer-cli
    build:
      context: .
      dockerfile: cli.Dockerfile
      args:
        - uid=${HOST_UID:-1000}
        - gid=${HOST_GID:-1000}
        - user=${HOST_USER}
        - app_root=${BACKEND_ROOT:-/var/www/html}/${LARAVEL_APP_NAME}
        - php_version=${PHP_VERSION:-8.2}
        - debug=${BACKEND_DEBUG:-}
        - tz=${TIMEZONE:-Etc/UTC}
        - redis_version=${REDIS_VERSION:-6.0.2}
    environment:
      - XDEBUG_SESSION=1
    volumes:
      - ./api/laravel:${BACKEND_ROOT:-/var/www/html}/${LARAVEL_APP_NAME}
    entrypoint: [ "composer" ]
    networks:
      - laravel_net
    tty: true
    stdin_open: true

  artisan-cli:
    container_name: artisan-cli
    build:
      context: .
      dockerfile: cli.Dockerfile
      args:
        - uid=${HOST_UID:-1000}
        - user=${HOST_USER}
        - gid=${HOST_GID:-1000}
        - app_root=${BACKEND_ROOT:-/var/www/html}/${LARAVEL_APP_NAME}
        - php_version=${PHP_VERSION:-8.2}
        - debug=${BACKEND_DEBUG:-}
        - tz=${TIMEZONE:-Etc/UTC}
        - redis_version=${REDIS_VERSION:-6.0.2}
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=33060
      - DB_DATABASE=${MYSQL_DB_NAME}
      - DB_USERNAME=${MYSQL_DB_USER:-laravel}
      - DB_PASSWORD=${MYSQL_DB_PASS:-}
      - APP_ENV=local
      - APP_DEBUG=true
      - REDIS_HOST=redis
      - MOCK_DATA=${MOCK_DATA:-no}
      - XDEBUG_SESSION=1
    env_file: ./.env
    volumes:
      - ./api/laravel:${BACKEND_ROOT:-/var/www/html}/${LARAVEL_APP_NAME}
    depends_on:
      - mysql
    entrypoint: [ "php", "${BACKEND_ROOT:-/var/www/html}/${LARAVEL_APP_NAME}/artisan" ]
    networks:
      - laravel_net
    tty: true
    stdin_open: true
    
  ui-vue:
    build:
      context: ./ui/vue
      args:
        - node_version=${APP_NODE_VERSION:-20.12.2}
        - app_root=${FRONTEND_ROOT:-/src}
        - uid=${HOST_UID:-1000}
        - user=${HOST_USER}
        - gid=${HOST_GID:-1000}
        - debug=${UI_DEBUG:-no}
        - pnpm_version=${PNPM_VERSION:-latest}
    env_file: ./.env
    ports:
      - "5173:5173"
    working_dir: ${FRONTEND_ROOT:-/src}
    networks:
      - laravel_net
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    volumes:
      - ./ui/vue:${FRONTEND_ROOT:-/src}
      # - npm_logs:/home/${HOST_USER}/.npm/_logs/
    depends_on:
      - php-api
      - api-gateway

  # mailhog:
  #   image: mailhog/mailhog:latest
  #   ports:
  #     - "1025:1025"
  #     - "8025:8025"
  #   networks:
  #     - laravel_net

  phpmyadmin:
    image: phpmyadmin:fpm-alpine
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=${MYSQL_PORT:-3306}
      - PMA_USER=${MYSQL_USER:-laravel}
      - PMA_PASSWORD=${MYSQL_DB_PASS}
      - PMA_UPLOADDIR=/tmp/phpmyadmin
      - PMA_PMADB=phpmyadmin
    networks:
      - laravel_net
    depends_on:
      - mysql

volumes:
  mysql_data_vol:
  redis_data:
  npm_logs:

networks:
  laravel_net:
    ipam:
      config:
        - subnet: 172.177.0.0/24