services:
  api-laravel:
    env_file:
      - ./api/laravel/.env
      - ./.env
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
      args:
        - uid=${HOST_UID:-1000}
        - user=${HOST_USER}
        - gid=${HOST_GID:-1000}
        - app_root=${BACKEND_ROOT}
        - debug=${BACKEND_DEBUG:-}
    environment:
      # Override Laravel environment variables
      # Full list: https://www.inmotionhosting.com/support/edu/laravel/understanding-the-laravel-env-file/
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=33060
      - DB_DATABASE=${MYSQL_DB_NAME}
      - DB_USERNAME=${MYSQL_DB_USER:-root}
      - DB_PASSWORD=${MYSQL_DB_PASS:-}
      - APP_ENV=local
      - APP_DEBUG=true
      - REDIS_HOST=redis
    ports:
      - "8000:80"
    volumes:
      - ./api/laravel:${BACKEND_ROOT}/${LARAVEL_APP_NAME:-laravel}:delegated
    depends_on:
      - redis
      - mysql
      - php
      # - mailhog
    networks:
      - laravel_net
    working_dir: ${BACKEND_ROOT}/${LARAVEL_APP_NAME:-laravel}

  php:
    build:
      dockerfile: Dockerfile
      args:
        - uid=${HOST_UID:-1000}
        - user=${HOST_USER}
        - gid=${HOST_GID:-1000}
        - app_root=${BACKEND_ROOT}/${LARAVEL_APP_NAME:-laravel}
        - redis_version=${REDIS_VERSION:-6.0.2}
        - php_version=${PHP_VERSION:-8.2}
        - debug=${BACKEND_DEBUG:-yes}
    environment:
      - XDEBUG_SESSION=1
      # - DB_CONNECTION=mysql
      # - DB_HOST=mysql
      # - DB_PORT=${MYSQL_DB_PORT:-3306}
      # - DB_DATABASE=${MYSQL_DB_NAME:-laravel}
      # - DB_USER=${MYSQL_USER:-laravel}
      # - DB_PASS=${MYSQL_DB_PASS}
    # volumes:
      # - ./api/laravel:${BACKEND_ROOT}/${LARAVEL_APP_NAME:-laravel}:delegated
      # - /docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - laravel_net
    working_dir: ${BACKEND_ROOT}/${LARAVEL_APP_NAME:-laravel}

  api-gateway:
    build:
      context: .
      dockerfile: ./docker/node/gateway.Dockerfile
      args:
        - node_version=${APP_NODE_VERSION}
        - app_root=${FRONTEND_ROOT:-/src}
        - uid=${HOST_UID:-1000}
        - user=${HOST_USER}
        - gid=${HOST_GID:-1000}
        - debug=${DEBUG:-no}
    working_dir: ${FRONTEND_ROOT:-/src}
    networks:
      - laravel_net
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    volumes:
      - ./api/gateway:${FRONTEND_ROOT:-/src}:delegated
    depends_on:
      - api-laravel

  mysql:
    image: mysql:8.0.37
    restart: on-failure
    tty: true
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      - MYSQL_DATABASE=${MYSQL_DB_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_DB_PASS}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_ROOT_HOST=%
      - MYSQL_LOG_CONSOLE=true
      - TZ=EEST
    networks:
      - laravel_net
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/laravel.cnf
      - ./docker/mysql/data/:/var/lib/mysql/
      - ./docker/mysql/log/mysql.log:/var/log/mysql/mysql.log
      - ./docker/mysql/log/error.log:/var/log/mysql/error.log
      - ./docker/mysql/log/mysql-slow.log:/var/log/mysql/mysql-slow.log
    # user: ${HOST_UID}:${HOST_GID}

  redis:
    image: redis:${REDIS_VERSION:-6.0.2}-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    sysctls:
      net.core.somaxconn: 1024
    networks:
      - laravel_net
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - redis_data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf

  composer:
    container_name: laravel_composer
    build:
      dockerfile: Dockerfile
      args:
        - uid=${HOST_UID:-1000}
        - gid=${HOST_GID:-1000}
        - user=${HOST_USER}
        - app_root=${BACKEND_ROOT}
        - redis_version=${REDIS_VERSION:-6.0.2}
        - php_version=${PHP_VERSION:-8.2}
        - debug=${BACKEND_DEBUG:-}
    depends_on:
      - php
    volumes:
      - ./api:${BACKEND_ROOT}
    entrypoint: [ "composer" ]
    networks:
      - laravel_net
    working_dir: ${BACKEND_ROOT}/${LARAVEL_APP_NAME:-laravel}

  artisan:
    container_name: laravel_artisan
    build:
      dockerfile: Dockerfile
      args:
        - uid=${HOST_UID:-1000}
        - user=${HOST_USER}
        - gid=${HOST_GID:-1000}
        - app_root=${BACKEND_ROOT}/${LARAVEL_APP_NAME:-laravel}
        - redis_version=${REDIS_VERSION:-6.0.2}
        - php_version=${PHP_VERSION:-8.2}
        - debug=${BACKEND_DEBUG:-}
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=${MYSQL_DB_PORT:-3306}
      - DB_DATABASE=${MYSQL_DB_NAME:-laravel}
      - DB_USER=${MYSQL_USER:-laravel}
      - DB_PASS=${MYSQL_DB_PASS}
    volumes:
      - ./api:${BACKEND_ROOT}:delegated
    depends_on:
      - mysql
    entrypoint: [ "php", "${BACKEND_ROOT}/${LARAVEL_APP_NAME:-laravel}/artisan" ]
    networks:
      - laravel_net
    working_dir: ${BACKEND_ROOT}/${LARAVEL_APP_NAME:-laravel}

  ui-vue:
    build:
      context: .
      dockerfile: ./docker/node/vue.Dockerfile
      args:
        - node_version=${APP_NODE_VERSION}
        - app_root=${FRONTEND_ROOT:-/src}
        - uid=${HOST_UID}
        - user=${HOST_USER}
        - gid=${HOST_GID}
        - debug=${DEBUG:-no}
    ports:
      - "5173:5173"
    working_dir: ${FRONTEND_ROOT:-/src}
    networks:
      - laravel_net
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    volumes:
      - ./ui/vue:${FRONTEND_ROOT:-/src}:delegated
      # - npm_logs:/home/${HOST_USER}/.npm/_logs/
    depends_on:
      - api-laravel
      - api-gateway

  # mailhog:
  #   image: mailhog/mailhog:latest
  #   ports:
  #     - "1025:1025"
  #     - "8025:8025"
  #   networks:
  #     - laravel_net

  phpmyadmin:
    image: phpmyadmin:fpm-alpine
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=${MYSQL_PORT:-3306}
      - PMA_USER=${MYSQL_USER:-laravel}
      - PMA_PASSWORD=${MYSQL_DB_PASS}
      - PMA_UPLOADDIR=/tmp/phpmyadmin
      - PMA_PMADB=phpmyadmin
    networks:
      - laravel_net
    depends_on:
      - mysql
      - php

volumes:
  mysql_data:
  redis_data:
  npm_logs:

networks:
  laravel_net:
    ipam:
      config:
        - subnet: 172.177.0.0/24