services:
  api-laravel:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
      args:
        - uid=${HOST_UID:-1000}
        - user=${HOST_USER}
        - gid=${HOST_GID:-1000}
        - app_root=${BACKEND_ROOT}
        - debug=${BACKEND_DEBUG:-}
    environment:
      - DB_CONNECTION=mysql
    ports:
      - "8000:80"
    volumes:
      - ./api:${BACKEND_ROOT}:delegated
    depends_on:
      - redis
      - mysql
      - php
      # - mailhog
    networks:
      - laravel_net
    working_dir: ${BACKEND_ROOT}/${LARAVEL_APP_NAME:-laravel}

  api-gateway:
    build:
      context: .
      dockerfile: ./docker/node/gateway.Dockerfile
      args:
        - node_version=${APP_NODE_VERSION}
        - app_root=${FRONTEND_ROOT:-/src}
        - uid=${HOST_UID:-1000}
        - user=${HOST_USER}
        - gid=${HOST_GID:-1000}
        - debug=${DEBUG:-no}
    working_dir: ${FRONTEND_ROOT:-/src}
    networks:
      - laravel_net
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    volumes:
      - ./api/gateway:${FRONTEND_ROOT:-/src}:delegated
    depends_on:
      - api-laravel

  mysql:
    image: mysql:8.0.37
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${SQL_DB_NAME}
      - MYSQL_USER=${SQL_USER}
      - MYSQL_PASSWORD=${SQL_DB_PASS}
      - MYSQL_ROOT_PASSWORD=${SQL_DB_ROOT_PASS}
      - MYSQL_ONETIME_PASSWORD=yes
    networks:
      - laravel_net
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:${REDIS_VERSION:-6.0.2}-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    sysctls:
      net.core.somaxconn: 1024
    networks:
      - laravel_net
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - redis_data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf

  composer:
    container_name: laravel_composer
    build:
      args:
        - uid=${HOST_UID:-1000}
        - gid=${HOST_GID:-1000}
        - user=${HOST_USER}
        - app_root=${BACKEND_ROOT}
        - redis_version=${REDIS_VERSION:-6.0.2}
        - php_version=${PHP_VERSION:-8.2}
        - debug=${BACKEND_DEBUG:-}
    depends_on:
      - php
    volumes:
      - ./api:${BACKEND_ROOT}
    entrypoint: [ "composer" ]
    networks:
      - laravel_net
    working_dir: ${BACKEND_ROOT}/${LARAVEL_APP_NAME:-laravel}

  ui-vue:
    build:
      context: .
      dockerfile: ./docker/node/vue.Dockerfile
      args:
        - node_version=${APP_NODE_VERSION}
        - app_root=${FRONTEND_ROOT:-/src}
        - uid=${HOST_UID}
        - user=${HOST_USER}
        - gid=${HOST_GID}
        - debug=${DEBUG:-no}
    ports:
      - "5173:5173"
    working_dir: ${FRONTEND_ROOT:-/src}
    networks:
      - laravel_net
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    volumes:
      - ./ui/vue:${FRONTEND_ROOT:-/src}:delegated
      # - npm_logs:/home/${HOST_USER}/.npm/_logs/
    depends_on:
      - api-laravel
      - api-gateway

  artisan:
    container_name: laravel_artisan
    build:
      args:
        - uid=${HOST_UID:-1000}
        - user=${HOST_USER}
        - gid=${HOST_GID:-1000}
        - app_root=${BACKEND_ROOT}/${LARAVEL_APP_NAME:-laravel}
        - redis_version=${REDIS_VERSION:-6.0.2}
        - php_version=${PHP_VERSION:-8.2}
        - debug=${BACKEND_DEBUG:-}
    volumes:
      - ./api:${BACKEND_ROOT}:delegated
    depends_on:
      - mysql
    entrypoint: [ "php", "${BACKEND_ROOT}/${LARAVEL_APP_NAME:-laravel}/artisan" ]
    networks:
      - laravel_net
    working_dir: ${BACKEND_ROOT}/${LARAVEL_APP_NAME:-laravel}

  # mailhog:
  #   image: mailhog/mailhog:latest
  #   ports:
  #     - "1025:1025"
  #     - "8025:8025"
  #   networks:
  #     - laravel_net

  phpmyadmin:
    image: phpmyadmin:fpm-alpine
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=${MYSQL_PORT:-3306}
      - PMA_USER=${SQL_USER:-laravel}
      - PMA_PASSWORD=${SQL_DB_PASS}
      - PMA_UPLOADDIR=/tmp/phpmyadmin
      - PMA_PMADB=phpmyadmin
    networks:
      - laravel_net
    depends_on:
      - mysql
      - php

  php:
    build:
      args:
        - uid=${HOST_UID:-1000}
        - user=${HOST_USER}
        - gid=${HOST_GID:-1000}
        - app_root=${BACKEND_ROOT}
        - redis_version=${REDIS_VERSION:-6.0.2}
        - php_version=${PHP_VERSION:-8.2}
        - debug=${BACKEND_DEBUG:-}
    volumes:
      - ./api:${BACKEND_ROOT}:delegated
    networks:
      - laravel_net
    working_dir: ${BACKEND_ROOT}/${LARAVEL_APP_NAME:-laravel}

volumes:
  mysql_data:
  redis_data:
  npm_logs:

networks:
  laravel_net:
    ipam:
      config:
        - subnet: 172.177.0.0/24